---
name: password_manager
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  provider: ^6.0.5
  modal_progress_hud: ^0.1.3
  http: ^0.13.5
  cupertino_icons: ^1.0.5
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  animated_button: ^0.2.0
  shimmer: ^2.0.0
  lottie: ^1.4.2
  image_picker: ^0.8.6+1
  firebase_storage: ^11.0.10
  fluttertoast: 8.1.2
  auto_size_text: ^3.0.0
  animations: ^2.0.7
  random_password_generator: ^0.2.1
  encryptor: ^0.0.1
  crypto: ^3.0.2
  local_session_timeout: 2.2.0
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
