// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVDTc4TNOXTRgWz-qmW8SEHW7G3O57OHw',
    appId: '1:318178908576:web:362f57019e59716901acc5',
    messagingSenderId: '318178908576',
    projectId: 'pwd-manager-90267',
    authDomain: 'pwd-manager-90267.firebaseapp.com',
    storageBucket: 'pwd-manager-90267.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQS9yCWnIoNNGVBoLQiOikTCNtZXkV4U',
    appId: '1:318178908576:android:ed08e6d16dbd1fdc01acc5',
    messagingSenderId: '318178908576',
    projectId: 'pwd-manager-90267',
    storageBucket: 'pwd-manager-90267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWS5AtjyLiUgjrlULz9AJ507Bw1yeIP8w',
    appId: '1:318178908576:ios:3319f5231e3e1e7201acc5',
    messagingSenderId: '318178908576',
    projectId: 'pwd-manager-90267',
    storageBucket: 'pwd-manager-90267.appspot.com',
    iosClientId: '318178908576-oonbcuv9cub1re47s6g5paannglerhla.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWS5AtjyLiUgjrlULz9AJ507Bw1yeIP8w',
    appId: '1:318178908576:ios:3319f5231e3e1e7201acc5',
    messagingSenderId: '318178908576',
    projectId: 'pwd-manager-90267',
    storageBucket: 'pwd-manager-90267.appspot.com',
    iosClientId: '318178908576-oonbcuv9cub1re47s6g5paannglerhla.apps.googleusercontent.com',
    iosBundleId: 'com.example.passwordManager',
  );
}
