name: FirebaseCI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
          flutter-version: "3.0.0"
          channel: 'stable'
          cache: true // 2
    
    - name: Get dependencies
      run: flutter pub get
      
    - name: Enable web Configuration
      run: flutter config --enable-web

    - name: Static Analysis by using DCM
      uses: dart-code-checker/dart-code-metrics-action@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        #fatal_warnings: true
      #run: flutter pub run dart_code_metrics:metrics --reporter=github lib

    #- name: Testing app
     # run: flutter test --coverage

    #- name: Upload coverage to Codecov
     # uses: codecov/codecov-action@v1
     # with:
      #  token: ${{ secrets.CODECOV_TOKEN }}
      # file: coverage/lcov.info



    - name: Build Web Application 
      run: flutter build web
    
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --public build/web
        cache: true // 2
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_CLI_TOKEN}}
        PROJECT_ID: pwd-manager-90267
